### ISSUE TITLE
saving settings fails when disabling all tests

### ISSUE THREAD

**Issue by poilu** [earnjam/site-health-tool-manager#3]
When all checkboxes in settings are unchecked and the 'Save Tests' button is clicked the configuration returns to the previously saved status.

**Comment by earnjam** [comment]
Thanks for the bug report. This is fixed with c7d07dbb217c0e5e5f92faca77ddd9dc37efe3eb. I'll get it into the next plugin release. 

I'd like to note though that if someone is going to disable all the tests, they should just use a different plugin that disables the site health tool entirely. Plugins or core might add more tests in the future, and then they would show up and be enabled. The purpose of this plugin is to manage certain aspects of the site health tool, not disable it completely.
